config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

  def contact
    @members = [ 'thanh', 'dimitri', 'germain', 'damien', 'julien' ]
    if params[:member]
      @members = @members.select { |member| member.start_with?(params[:member]) }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Our first view 🚀</h1>

<% members = [ 'thanh', 'dimitri', 'germain', 'damien', 'julien' ] %>

<h2>Meet our team</h2>
<ol>
  <% members.each do |member| %>
    <li><%= member.capitalize %></li>
  <% end %>
</ol>

<%= link_to "Meet our team", contact_path %>

app/views/pages/contact.html.erb
<ol>
  <% @members.each do |member| %>
    <li><%= member.capitalize %></li>
  <% end %>
</ol>

<form action="/contact" method="get">
  <input type="text" name="member" placeholder="Who are you looking for?">
  <input type="submit">
</form>

<%= link_to "Meet our team", about_path %>